import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:go_router/go_router.dart';
import '../models/purchase.dart';
import '../models/product.dart';
import '../models/contact.dart';
import '../providers/purchase_provider.dart';
import '../providers/supplier_provider.dart';
import '../providers/product_provider.dart';
import '../models/supplier.dart';
import '../models/customer_bank_account.dart';
import '../services/config_service.dart';
import '../widgets/responsive_layout.dart';
import '../widgets/searchable_dropdown.dart';
import '../utils/error_dialog.dart';

class PurchaseFormScreen extends StatefulWidget {
  final Purchase? purchase;
  final String? purchaseId;
  final String? duplicateId;

  const PurchaseFormScreen({Key? key, this.purchase, this.purchaseId, this.duplicateId}) : super(key: key);

  @override
  State<PurchaseFormScreen> createState() => _PurchaseFormScreenState();
}

class _PurchaseFormScreenState extends State<PurchaseFormScreen> {
  final _formKey = GlobalKey<FormState>();
  final _purchaseDateController = TextEditingController();
  final _invoiceNumberController = TextEditingController();
  final _paymentMethodController = TextEditingController();
  final _customerAccountController = TextEditingController();
  final _paymentDateController = TextEditingController();
  final _ourAccountController = TextEditingController();
  final _warehouseNotesController = TextEditingController();
  final _notesController = TextEditingController(); // ใหม่: รายละเอียด
  final _shippingCostController = TextEditingController();
  final _actualShippingController = TextEditingController();

  String? _selectedSupplierId;
  String? _selectedAccountId;
  int _selectedContactIndex = 0; // Index ของผู้ติดต่อที่เลือก (default = 0 = primary)
  int? _selectedSupplierBankIndex; // Index ของบัญชี supplier ที่เลือก (null = กรอกเอง)
  bool _isVAT = false;
  String _vatType = 'exclusive'; // "exclusive" (VAT นอก) or "inclusive" (VAT ใน)
  bool _isPaid = false;
  bool _isWarehouseUpdated = false;
  List<PurchaseItem> _purchaseItems = [];
  List<WarehouseItem> _warehouseItems = [];

  bool _isLoading = false;
  bool get _isEdit => widget.purchase != null || widget.purchaseId != null;

  @override
  void initState() {
    super.initState();
    _initializeForm();
  }

  @override
  void dispose() {
    _purchaseDateController.dispose();
    _invoiceNumberController.dispose();
    _paymentMethodController.dispose();
    _customerAccountController.dispose();
    _paymentDateController.dispose();
    _ourAccountController.dispose();
    _warehouseNotesController.dispose();
    _notesController.dispose();
    _shippingCostController.dispose();
    _actualShippingController.dispose();
    super.dispose();
  }

  Future<void> _initializeForm() async {
    // Load data first
    await _loadData();
    
    // Force rebuild after data loaded
    if (mounted) {
      setState(() {});
    }
    
    // Then populate fields
    if (widget.purchase != null) {
      _populateFields();
    } else if (widget.purchaseId != null) {
      _loadPurchaseFromId();
    } else if (widget.duplicateId != null) {
      _loadDuplicatePurchase();
    }
  }

  void _loadDuplicatePurchase() {
    WidgetsBinding.instance.addPostFrameCallback((_) async {
      final purchaseProvider = context.read<PurchaseProvider>();
      
      if (purchaseProvider.allPurchases.isEmpty) {
        await purchaseProvider.loadPurchases();
      }
      
      final purchase = purchaseProvider.getPurchaseById(widget.duplicateId!);
      if (purchase != null) {
        _populateFieldsForDuplicate(purchase);
      }
    });
  }

  void _populateFieldsForDuplicate(Purchase purchase) {
    // Copy all fields except purchaseCode (will be generated by server)
    _purchaseDateController.text = _formatDate(DateTime.now()); // Use current date
    _selectedSupplierId = purchase.supplierId;
    _isVAT = purchase.isVAT;
    _shippingCostController.text = purchase.shippingCost > 0 ? purchase.shippingCost.toString() : '';
    _actualShippingController.text = purchase.warehouse.actualShipping > 0 ? purchase.warehouse.actualShipping.toString() : '';
    _notesController.text = purchase.notes ?? '';
    
    // Copy items
    _purchaseItems = purchase.items.map((item) => PurchaseItem(
      productId: item.productId,
      productName: item.productName,
      productCode: item.productCode,
      quantity: item.quantity,
      unitPrice: item.unitPrice,
      totalPrice: item.totalPrice,
    )).toList();
    
    // Reset payment and warehouse info for new purchase
    _isPaid = false;
    _paymentMethodController.text = '';
    _customerAccountController.text = '';
    _paymentDateController.text = '';
    _ourAccountController.text = '';
    _selectedAccountId = null;
    _isWarehouseUpdated = false;
    _warehouseNotesController.text = '';
    _warehouseItems = [];
    
    if (mounted) {
      setState(() {});
    }
  }

  Future<void> _loadData() async {
    final supplierProvider = context.read<SupplierProvider>();
    final productProvider = context.read<ProductProvider>();
    
    // Load only if not already loaded
    final futures = <Future>[];
    
    if (supplierProvider.allSuppliers.isEmpty && !supplierProvider.isLoading) {
      futures.add(supplierProvider.loadSuppliers());
    }
    
    if (productProvider.allProducts.isEmpty && !productProvider.isLoading) {
      futures.add(productProvider.loadProducts());
    }
    
    if (!ConfigService().isLoaded) {
      futures.add(ConfigService().loadConfig());
    }
    
    if (futures.isNotEmpty) {
      await Future.wait(futures);
    }
  }

  void _loadPurchaseFromId() {
    WidgetsBinding.instance.addPostFrameCallback((_) {
      final purchase = context.read<PurchaseProvider>().getPurchaseById(widget.purchaseId!);
      if (purchase != null) {
        _populateFieldsFromPurchase(purchase);
      }
    });
  }

  void _populateFieldsFromPurchase(Purchase purchase) {
    _purchaseDateController.text = _formatDate(purchase.purchaseDate);
    _invoiceNumberController.text = purchase.invoiceNumber ?? '';
    _selectedSupplierId = purchase.supplierId;
    _isVAT = purchase.isVAT;
    _vatType = purchase.vatType;
    _isPaid = purchase.payment.isPaid;
    _paymentMethodController.text = purchase.payment.paymentMethod ?? '';
    _selectedAccountId = purchase.payment.ourAccount;
    _customerAccountController.text = purchase.payment.customerAccount ?? '';
    _paymentDateController.text = purchase.payment.paymentDate != null 
        ? _formatDate(purchase.payment.paymentDate!) 
        : '';
    _isWarehouseUpdated = purchase.warehouse.isUpdated;
    _warehouseNotesController.text = purchase.warehouse.notes ?? '';
    _notesController.text = purchase.notes ?? '';
    _shippingCostController.text = purchase.shippingCost.toString();
    _actualShippingController.text = purchase.warehouse.actualShipping.toString();
    _purchaseItems = List.from(purchase.items);
    _warehouseItems = List.from(purchase.warehouse.items);
    
    if (mounted) {
      WidgetsBinding.instance.addPostFrameCallback((_) {
        setState(() {});
      });
    }
  }

  void _populateFields() {
    final purchase = widget.purchase!;
    _populateFieldsFromPurchase(purchase);
  }

  @override
  Widget build(BuildContext context) {
    final purchaseId = widget.purchase?.id ?? widget.purchaseId;
    
    return Scaffold(
      appBar: ResponsiveAppBar(
        title: _isEdit ? 'แก้ไขรายการซื้อ' : 'เพิ่มรายการซื้อใหม่',
        leading: _isEdit && purchaseId != null
            ? IconButton(
                icon: const Icon(Icons.arrow_back),
                onPressed: () => context.pop(),
                tooltip: 'กลับไปหน้ารายละเอียด',
              )
            : null,
        actions: [
          if (_isLoading)
            const Padding(
              padding: EdgeInsets.all(16),
              child: SizedBox(
                width: 20,
                height: 20,
                child: CircularProgressIndicator(strokeWidth: 2),
              ),
            ),
        ],
      ),
      body: Form(
        key: _formKey,
        child: ResponsivePadding(
          child: SingleChildScrollView(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                // Basic Info Section
                _buildBasicInfoSection(),
                
                const SizedBox(height: 24),
                
                // VAT Section
                _buildVATSection(),
                
                const SizedBox(height: 24),
                
                // Purchase Items Section
                _buildPurchaseItemsSection(),
                
                const SizedBox(height: 24),
                
                // Payment Section
                _buildPaymentSection(),
                
                const SizedBox(height: 24),
                
                // Warehouse Section
                _buildWarehouseSection(),
                
                const SizedBox(height: 32),
                
                // Action Buttons
                _buildActionButtons(_isEdit),
              ],
            ),
          ),
        ),
      ),
    );
  }

  Widget _buildBasicInfoSection() {
    return Card(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            ResponsiveText(
              'ข้อมูลพื้นฐาน',
              style: const TextStyle(
                fontSize: 16,
                fontWeight: FontWeight.bold,
              ),
            ),
            const SizedBox(height: 16),
            
            // Purchase Date
            _buildDateField(
              controller: _purchaseDateController,
              label: 'วันที่ซื้อ *',
              onTap: () => _selectDate(_purchaseDateController),
            ),
            
            const SizedBox(height: 16),
            
            // Invoice Number
            _buildTextField(
              controller: _invoiceNumberController,
              label: 'เลขที่ Invoice',
              hint: 'กรอกเลขที่ Invoice (ถ้ามี)',
            ),
            
            const SizedBox(height: 16),
            
            // Customer Selection
            _buildSupplierDropdown(),
            
            const SizedBox(height: 16),
            
            // Shipping Cost
            _buildTextField(
              controller: _shippingCostController,
              label: 'ค่าส่ง',
              hint: '0.00',
              keyboardType: const TextInputType.numberWithOptions(decimal: true),
            ),
            
            const SizedBox(height: 16),
            
            // Notes
            _buildTextField(
              controller: _notesController,
              label: 'รายละเอียด',
              hint: 'กรอกรายละเอียดเพิ่มเติม...',
              maxLines: 3,
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildPurchaseItemsSection() {
    return Card(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                ResponsiveText(
                  'สินค้าที่ซื้อ',
                  style: const TextStyle(
                    fontSize: 16,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                ElevatedButton.icon(
                  onPressed: _addPurchaseItem,
                  icon: const Icon(Icons.add, size: 16),
                  label: const Text('เพิ่มสินค้า'),
                  style: ElevatedButton.styleFrom(
                    padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
                  ),
                ),
              ],
            ),
            const SizedBox(height: 16),
            
            if (_purchaseItems.isEmpty)
              Container(
                padding: const EdgeInsets.all(16),
                decoration: BoxDecoration(
                  color: Colors.grey[100],
                  borderRadius: BorderRadius.circular(8),
                  border: Border.all(color: Colors.grey[300]!),
                ),
                child: Row(
                  children: [
                    Icon(Icons.info_outline, color: Colors.grey[600]),
                    const SizedBox(width: 8),
                    Expanded(
                      child: ResponsiveText(
                        'ยังไม่มีสินค้าในรายการ\nกดปุ่ม "เพิ่มสินค้า" เพื่อเพิ่มสินค้า',
                        style: TextStyle(
                          color: Colors.grey[600],
                          fontSize: 14,
                        ),
                      ),
                    ),
                  ],
                ),
              )
            else
              ...List.generate(_purchaseItems.length, (index) {
                return _buildPurchaseItemRow(index);
              }),
              
            // Total Summary
            if (_purchaseItems.isNotEmpty) ...[
              const SizedBox(height: 16),
              _buildTotalSummary(),
            ],
          ],
        ),
      ),
    );
  }

  Widget _buildVATSection() {
    return Card(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
          children: [
            ResponsiveText(
                  'ข้อมูล VAT *',
              style: const TextStyle(
                fontSize: 16,
                fontWeight: FontWeight.bold,
              ),
                ),
                if (_isEdit)
                  Padding(
                    padding: const EdgeInsets.only(left: 8),
                    child: Icon(Icons.lock, size: 16, color: Colors.grey[400]),
                  ),
              ],
            ),
            const SizedBox(height: 16),
            
            // VAT Radio buttons
            Row(
                children: [
                Expanded(
                  child: RadioListTile<bool>(
                    title: Text(
                      'ไม่มี VAT',
                    style: TextStyle(
                        fontSize: 14,
                      color: _isEdit ? Colors.grey : null,
                    ),
                  ),
                    value: false,
                    groupValue: _isVAT,
                    onChanged: _isEdit ? null : (value) {
                      setState(() {
                        _isVAT = value ?? false;
                      });
                    },
                    contentPadding: EdgeInsets.zero,
                    dense: true,
                  ),
                ),
                Expanded(
                  child: RadioListTile<bool>(
                    title: Text(
                      'มี VAT (7%)',
                      style: TextStyle(
                        fontSize: 14,
                        color: _isEdit ? Colors.grey : null,
                    ),
              ),
                    value: true,
                    groupValue: _isVAT,
              onChanged: _isEdit ? null : (value) {
                setState(() {
                  _isVAT = value ?? false;
                });
              },
                    contentPadding: EdgeInsets.zero,
                    dense: true,
                  ),
                ),
              ],
            ),
            
            // VAT Type selector (only show when VAT is selected)
            if (_isVAT) ...[
              const SizedBox(height: 8),
              Padding(
                padding: const EdgeInsets.symmetric(horizontal: 16),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      'วิธีคำนวณ VAT${_isEdit ? ' (ไม่สามารถเปลี่ยนได้)' : ''}',
                      style: TextStyle(
                        fontWeight: FontWeight.w500,
                        color: _isEdit ? Colors.grey : null,
                      ),
                    ),
                    const SizedBox(height: 8),
                    Row(
                      children: [
                        Expanded(
                          child: RadioListTile<String>(
                            title: const Text('VAT นอก', style: TextStyle(fontSize: 14)),
                            subtitle: const Text('ราคา + VAT 7%', style: TextStyle(fontSize: 12)),
                            value: 'exclusive',
                            groupValue: _vatType,
                            onChanged: _isEdit ? null : (value) {
                              setState(() {
                                _vatType = value ?? 'exclusive';
                              });
                            },
                            contentPadding: EdgeInsets.zero,
                            dense: true,
                          ),
                        ),
                        Expanded(
                          child: RadioListTile<String>(
                            title: const Text('VAT ใน', style: TextStyle(fontSize: 14)),
                            subtitle: const Text('ราคารวม VAT แล้ว', style: TextStyle(fontSize: 12)),
                            value: 'inclusive',
                            groupValue: _vatType,
                            onChanged: _isEdit ? null : (value) {
                              setState(() {
                                _vatType = value ?? 'exclusive';
                              });
                            },
                            contentPadding: EdgeInsets.zero,
                            dense: true,
            ),
                        ),
                      ],
                    ),
                  ],
                ),
              ),
            ],
          ],
        ),
      ),
    );
  }

  Widget _buildPaymentSection() {
    return Card(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            ResponsiveText(
              'ข้อมูลการชำระเงิน',
              style: const TextStyle(
                fontSize: 16,
                fontWeight: FontWeight.bold,
              ),
            ),
            const SizedBox(height: 16),
            
            // Payment Status Radio
            const Text(
              'สถานะการชำระเงิน *',
              style: TextStyle(fontWeight: FontWeight.w500),
            ),
            const SizedBox(height: 8),
            Row(
              children: [
                Expanded(
                  child: RadioListTile<bool>(
                    title: const Text('ค้างชำระ', style: TextStyle(fontSize: 14)),
                    value: false,
                    groupValue: _isPaid,
              onChanged: (value) {
                setState(() {
                  _isPaid = value ?? false;
                });
              },
                    contentPadding: EdgeInsets.zero,
                    dense: true,
                  ),
                ),
                Expanded(
                  child: RadioListTile<bool>(
                    title: const Text('จ่ายเงินแล้ว', style: TextStyle(fontSize: 14)),
                    value: true,
                    groupValue: _isPaid,
                    onChanged: (value) {
                      setState(() {
                        _isPaid = value ?? false;
                      });
                    },
                    contentPadding: EdgeInsets.zero,
                    dense: true,
                  ),
                ),
              ],
            ),
            
            const SizedBox(height: 16),
            _buildTextField(
              controller: _paymentMethodController,
              label: 'วิธีการชำระเงิน',
              hint: 'เช่น โอนเงิน, เงินสด, เช็ค',
            ),
            const SizedBox(height: 16),
            _buildAccountDropdown(),
            const SizedBox(height: 16),
            _buildSupplierBankAccountDropdown(),
            const SizedBox(height: 16),
            _buildDateField(
              controller: _paymentDateController,
              label: 'วันที่จ่ายเงิน',
              onTap: () => _selectDate(_paymentDateController),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildWarehouseSection() {
    return Card(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                ResponsiveText(
                  'ข้อมูลคลังสินค้า',
                  style: const TextStyle(
                    fontSize: 16,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                Row(
                  children: [
                    ElevatedButton.icon(
                      onPressed: _copyFromPurchaseItems,
                      icon: const Icon(Icons.copy, size: 16),
                      label: const Text('คัดลอกจากซื้อ'),
                      style: ElevatedButton.styleFrom(
                        padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
                      ),
                    ),
                    const SizedBox(width: 8),
                    ElevatedButton.icon(
                      onPressed: _addWarehouseItem,
                      icon: const Icon(Icons.add, size: 16),
                      label: const Text('เพิ่มสินค้า'),
                      style: ElevatedButton.styleFrom(
                        padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
                      ),
                    ),
                  ],
                ),
              ],
            ),
            const SizedBox(height: 16),
            
            CheckboxListTile(
              title: const Text('อัปเดตคลังแล้ว'),
              value: _isWarehouseUpdated,
              onChanged: (value) {
                setState(() {
                  _isWarehouseUpdated = value ?? false;
                });
              },
              controlAffinity: ListTileControlAffinity.leading,
            ),
            
            const SizedBox(height: 16),
            _buildTextField(
              controller: _actualShippingController,
              label: 'ค่าส่งจริง',
              hint: '0.00',
              keyboardType: const TextInputType.numberWithOptions(decimal: true),
            ),
            
            const SizedBox(height: 16),
            _buildTextField(
              controller: _warehouseNotesController,
              label: 'หมายเหตุคลังสินค้า',
              hint: 'ข้อมูลเพิ่มเติมเกี่ยวกับการรับสินค้า',
              maxLines: 3,
            ),
            
            const SizedBox(height: 16),
            
            // Warehouse Items List
            if (_warehouseItems.isNotEmpty) ...[
              ResponsiveText(
                'รายการสินค้าคลัง',
                style: const TextStyle(
                  fontSize: 14,
                  fontWeight: FontWeight.w600,
                ),
              ),
              const SizedBox(height: 8),
              ...List.generate(_warehouseItems.length, (index) {
                return _buildWarehouseItemRow(index);
              }),
            ],
          ],
        ),
      ),
    );
  }

  Widget _buildSupplierDropdown() {
    return Consumer<SupplierProvider>(
      builder: (context, supplierProvider, child) {
        // แสดง loading indicator ถ้ากำลังโหลด
        if (supplierProvider.isLoading) {
          return Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const Text(
                'ซัพพลายเออร์ *',
                style: TextStyle(fontWeight: FontWeight.w500, fontSize: 14),
              ),
              const SizedBox(height: 8),
              Container(
                padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 16),
                decoration: BoxDecoration(
                  border: Border.all(color: Colors.grey[300]!),
                  borderRadius: BorderRadius.circular(4),
                ),
                child: const Row(
                  children: [
                    Icon(Icons.local_shipping, color: Colors.grey),
                    SizedBox(width: 12),
                    SizedBox(
                      width: 16,
                      height: 16,
                      child: CircularProgressIndicator(strokeWidth: 2),
                    ),
                    SizedBox(width: 8),
                    Text('กำลังโหลดข้อมูลซัพพลายเออร์...', style: TextStyle(color: Colors.grey)),
                  ],
                ),
              ),
            ],
          );
        }
        
        // ดึงข้อมูลผู้ติดต่อของ supplier ที่เลือก
        Supplier? selectedSupplier;
        List<Contact> contacts = [];
        if (_selectedSupplierId != null) {
          selectedSupplier = supplierProvider.allSuppliers.firstWhere(
            (s) => s.id == _selectedSupplierId,
            orElse: () => supplierProvider.allSuppliers.first,
          );
          // ดึง contacts หรือสร้างจาก legacy fields
          if (selectedSupplier.contacts.isNotEmpty) {
            contacts = selectedSupplier.contacts;
          } else if (selectedSupplier.contactName.isNotEmpty) {
            contacts = [Contact(name: selectedSupplier.contactName, phone: selectedSupplier.phone, isDefault: true)];
          }
        }
        
        return Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            SearchableDropdown<String>(
              value: _selectedSupplierId,
              items: supplierProvider.allSuppliers.map((supplier) => supplier.id).toList(),
              itemAsString: (supplierId) {
                final supplier = supplierProvider.allSuppliers.firstWhere((s) => s.id == supplierId);
                return _formatSupplierDisplay(supplier);
          },
              itemAsValue: (supplierId) => supplierId,
          onChanged: (value) {
            setState(() {
                  _selectedSupplierId = value;
                  _selectedContactIndex = 0; // Reset to primary contact
            });
          },
              hint: 'เลือกซัพพลายเออร์',
              label: 'ซัพพลายเออร์ *',
          validator: (value) {
            if (value == null || value.isEmpty) {
                  return 'กรุณาเลือกซัพพลายเออร์';
            }
            return null;
          },
              prefixIcon: const Icon(Icons.local_shipping),
            ),
            
            // แสดง dropdown ผู้ติดต่อถ้ามีมากกว่า 1 คน
            if (contacts.length > 1) ...[
              const SizedBox(height: 16),
              _buildContactDropdown(contacts),
            ] else if (contacts.length == 1) ...[
              const SizedBox(height: 8),
              Container(
                padding: const EdgeInsets.all(8),
                decoration: BoxDecoration(
                  color: Colors.blue.shade50,
                  borderRadius: BorderRadius.circular(4),
                ),
                child: Row(
                  children: [
                    const Icon(Icons.person, size: 16, color: Colors.blue),
                    const SizedBox(width: 8),
                    Text(
                      'ผู้ติดต่อ: ${contacts[0].name} (${contacts[0].phone})',
                      style: const TextStyle(fontSize: 13),
                    ),
                  ],
                ),
              ),
            ],
          ],
        );
      },
    );
  }

  Widget _buildContactDropdown(List<Contact> contacts) {
    // หา index ของ primary contact
    int primaryIndex = contacts.indexWhere((c) => c.isDefault);
    if (primaryIndex == -1) primaryIndex = 0;
    
    // ถ้ายังไม่ได้เลือก ให้เลือก primary
    if (_selectedContactIndex >= contacts.length) {
      _selectedContactIndex = primaryIndex;
    }
    
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        const Text(
          'ผู้ติดต่อ',
          style: TextStyle(fontWeight: FontWeight.w500, fontSize: 14),
        ),
        const SizedBox(height: 8),
        DropdownButtonFormField<int>(
          value: _selectedContactIndex,
          decoration: InputDecoration(
            border: OutlineInputBorder(borderRadius: BorderRadius.circular(8)),
            contentPadding: const EdgeInsets.symmetric(horizontal: 12, vertical: 12),
          prefixIcon: const Icon(Icons.person),
          ),
          items: contacts.asMap().entries.map((entry) {
            final index = entry.key;
            final contact = entry.value;
            return DropdownMenuItem<int>(
              value: index,
              child: Row(
                children: [
                  Text('${contact.name} (${contact.phone})'),
                  if (contact.isDefault) ...[
                    const SizedBox(width: 8),
                    Container(
                      padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 2),
                      decoration: BoxDecoration(
                        color: Colors.blue,
                        borderRadius: BorderRadius.circular(8),
                      ),
                      child: const Text('หลัก', style: TextStyle(color: Colors.white, fontSize: 10)),
                    ),
                  ],
                ],
              ),
            );
          }).toList(),
          onChanged: (value) {
            setState(() {
              _selectedContactIndex = value ?? 0;
            });
          },
        ),
      ],
    );
  }

  Widget _buildSupplierBankAccountDropdown() {
    return Consumer<SupplierProvider>(
      builder: (context, supplierProvider, child) {
        // ดึงบัญชีของ supplier ที่เลือก
        List<CustomerBankAccount> supplierBankAccounts = [];
        if (_selectedSupplierId != null) {
          final supplier = supplierProvider.allSuppliers.firstWhere(
            (s) => s.id == _selectedSupplierId,
            orElse: () => supplierProvider.allSuppliers.first,
          );
          supplierBankAccounts = supplier.bankAccounts;
        }

        return Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            ResponsiveText(
              'บัญชีรับเงินของซัพพลายเออร์',
              style: const TextStyle(
                fontWeight: FontWeight.w500,
                fontSize: 14,
              ),
            ),
            const SizedBox(height: 8),
            
            // ถ้า supplier มีบัญชี แสดง dropdown + ตัวเลือกกรอกเอง
            if (supplierBankAccounts.isNotEmpty) ...[
              DropdownButtonFormField<int?>(
                value: _selectedSupplierBankIndex,
                decoration: InputDecoration(
                  border: OutlineInputBorder(borderRadius: BorderRadius.circular(8)),
                  contentPadding: const EdgeInsets.symmetric(horizontal: 12, vertical: 12),
                  prefixIcon: const Icon(Icons.account_balance),
                ),
                hint: const Text('เลือกบัญชี หรือกรอกเอง'),
                items: [
                  // ตัวเลือกกรอกเอง
                  const DropdownMenuItem<int?>(
                    value: null,
                    child: Text('กรอกเอง...', style: TextStyle(fontStyle: FontStyle.italic)),
                  ),
                  // บัญชีจาก supplier
                  ...supplierBankAccounts.asMap().entries.map((entry) {
                    final index = entry.key;
                    final account = entry.value;
                    return DropdownMenuItem<int?>(
                      value: index,
                      child: Row(
                        children: [
                          Expanded(
                            child: Text(
                              '${account.bankName} - ${account.accountNumber}',
                              overflow: TextOverflow.ellipsis,
                            ),
                          ),
                          if (account.isDefault)
                            Container(
                              margin: const EdgeInsets.only(left: 8),
                              padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 2),
                              decoration: BoxDecoration(
                                color: Colors.green,
                                borderRadius: BorderRadius.circular(8),
                              ),
                              child: const Text('หลัก', style: TextStyle(color: Colors.white, fontSize: 10)),
                            ),
                        ],
                      ),
                    );
                  }).toList(),
                ],
                onChanged: (value) {
                  setState(() {
                    _selectedSupplierBankIndex = value;
                    // ถ้าเลือกบัญชีจาก dropdown ให้ set ค่า
                    if (value != null && value < supplierBankAccounts.length) {
                      final account = supplierBankAccounts[value];
                      _customerAccountController.text = '${account.bankName} ${account.accountName} ${account.accountNumber}';
                    } else {
                      _customerAccountController.text = '';
                    }
                  });
                },
              ),
              
              // ถ้าเลือก "กรอกเอง" แสดง TextField
              if (_selectedSupplierBankIndex == null) ...[
                const SizedBox(height: 12),
                TextFormField(
                  controller: _customerAccountController,
                  decoration: InputDecoration(
                    hintText: 'กรอกเลขบัญชีหรือชื่อบัญชี',
                    border: OutlineInputBorder(borderRadius: BorderRadius.circular(8)),
                    contentPadding: const EdgeInsets.symmetric(horizontal: 12, vertical: 12),
                  ),
                ),
              ],
            ] else ...[
              // ถ้า supplier ไม่มีบัญชี แสดงแค่ TextField
              TextFormField(
                controller: _customerAccountController,
                decoration: InputDecoration(
                  hintText: 'กรอกเลขบัญชีหรือชื่อบัญชี',
                  border: OutlineInputBorder(borderRadius: BorderRadius.circular(8)),
                  contentPadding: const EdgeInsets.symmetric(horizontal: 12, vertical: 12),
                  prefixIcon: const Icon(Icons.account_balance),
                ),
              ),
              if (_selectedSupplierId != null)
                Padding(
                  padding: const EdgeInsets.only(top: 4),
                  child: Text(
                    'ซัพพลายเออร์นี้ยังไม่มีข้อมูลบัญชี',
                    style: TextStyle(color: Colors.grey.shade600, fontSize: 12),
                  ),
                ),
            ],
          ],
        );
      },
    );
  }

  Widget _buildAccountDropdown() {
    final configService = ConfigService();
    
    return FutureBuilder<void>(
      future: configService.isLoaded ? Future.value() : configService.loadConfig(),
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              ResponsiveText(
                'บัญชีที่ใช้จ่าย *',
                style: const TextStyle(
                  fontWeight: FontWeight.w500,
                  fontSize: 14,
                ),
              ),
              const SizedBox(height: 8),
              Container(
                padding: const EdgeInsets.all(12),
                decoration: BoxDecoration(
                  border: Border.all(color: Colors.grey),
                  borderRadius: BorderRadius.circular(8),
                ),
                child: const Row(
                  children: [
                    SizedBox(
                      width: 16,
                      height: 16,
                      child: CircularProgressIndicator(strokeWidth: 2),
                    ),
                    SizedBox(width: 8),
                    Text('กำลังโหลดบัญชี...'),
                  ],
                ),
              ),
            ],
          );
        }
        
        if (snapshot.hasError) {
          return Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              ResponsiveText(
                'บัญชีที่ใช้จ่าย *',
                style: const TextStyle(
                  fontWeight: FontWeight.w500,
                  fontSize: 14,
                ),
              ),
              const SizedBox(height: 8),
              Container(
                padding: const EdgeInsets.all(12),
                decoration: BoxDecoration(
                  border: Border.all(color: Colors.red),
                  borderRadius: BorderRadius.circular(8),
                ),
                child: Text('Error: ${snapshot.error}'),
              ),
            ],
          );
        }
        
         final accounts = configService.accounts;

         return Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            ResponsiveText(
              'บัญชีที่ใช้จ่าย *',
              style: const TextStyle(
                fontWeight: FontWeight.w500,
                fontSize: 14,
              ),
            ),
            const SizedBox(height: 8),
            DropdownButtonFormField<String>(
              value: _selectedAccountId,
              decoration: InputDecoration(
                border: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(8),
                ),
                contentPadding: const EdgeInsets.symmetric(
                  horizontal: 12,
                  vertical: 12,
                ),
              ),
              hint: const Text('เลือกบัญชี'),
              items: accounts.map((account) {
                return DropdownMenuItem<String>(
                  value: account.id,
                  child: Text(account.displayName),
                );
              }).toList(),
               onChanged: (String? newValue) {
                 setState(() {
                   _selectedAccountId = newValue;
                 });
               },
              validator: (value) {
                if (value == null || value.isEmpty) {
                  return 'กรุณาเลือกบัญชี';
                }
                return null;
              },
            ),
          ],
        );
      },
    );
  }

  Widget _buildPurchaseItemRow(int index) {
    final item = _purchaseItems[index];
    
    // Calculate VAT based on VAT type
    double vatAmount = 0.0;
    double priceBeforeVAT = item.totalPrice;
    double itemTotalWithVAT = item.totalPrice;
    
    if (_isVAT) {
      if (_vatType == 'inclusive') {
        // VAT ใน: ราคารวม VAT แล้ว, ต้องถอด VAT ออก
        // ราคาก่อน VAT = ราคารวม / 1.07
        priceBeforeVAT = item.totalPrice / 1.07;
        vatAmount = item.totalPrice - priceBeforeVAT;
        itemTotalWithVAT = item.totalPrice; // ราคาที่กรอกคือราคารวม VAT แล้ว
      } else {
        // VAT นอก: ราคา + VAT 7%
        vatAmount = item.totalPrice * 0.07;
        itemTotalWithVAT = item.totalPrice + vatAmount;
      }
    }
    
    return Container(
      margin: const EdgeInsets.only(bottom: 16),
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(
        color: Colors.blue[50],
        borderRadius: BorderRadius.circular(8),
        border: Border.all(color: Colors.blue[200]!),
      ),
      child: Column(
        children: [
          Row(
            children: [
              Expanded(
                child: Text(
                  '${item.productName} (${item.productCode})',
                  style: const TextStyle(
                    fontWeight: FontWeight.bold,
                    color: Colors.blue,
                  ),
                ),
              ),
              IconButton(
                onPressed: () => _removePurchaseItem(index),
                icon: const Icon(Icons.delete, color: Colors.red, size: 20),
                tooltip: 'ลบสินค้านี้',
              ),
            ],
          ),
          const SizedBox(height: 12),
          Row(
            children: [
              Expanded(
                child: Text('จำนวน: ${item.quantity}'),
              ),
              Expanded(
                child: Text('ราคาต่อชิ้น: ฿${item.unitPrice.toStringAsFixed(2)}'),
              ),
              Expanded(
                child: Text(
                  'รวม: ฿${item.totalPrice.toStringAsFixed(2)}',
                  style: const TextStyle(fontWeight: FontWeight.bold),
                ),
              ),
            ],
          ),
          if (_isVAT) ...[
            const SizedBox(height: 8),
            Row(
              children: [
                Expanded(
                  child: Text(
                    'VAT (7%): ฿${vatAmount.toStringAsFixed(2)}',
                    style: TextStyle(
                      color: Colors.green[700],
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ),
                Expanded(
                  child: Text(
                    'รวม VAT: ฿${itemTotalWithVAT.toStringAsFixed(2)}',
                    style: TextStyle(
                      color: Colors.green[700],
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                ),
              ],
            ),
          ],
        ],
      ),
    );
  }

  Widget _buildTotalSummary() {
    final totalBeforeVAT = _purchaseItems.fold(0.0, (sum, item) => sum + item.totalPrice);
    
    // Calculate VAT based on VAT type
    double totalVAT = 0.0;
    double grandTotal = 0.0;
    
    if (_isVAT) {
      if (_vatType == 'inclusive') {
        // VAT ใน: ราคารวม VAT แล้ว, ต้องถอด VAT ออก
        // ราคาก่อน VAT = ราคารวม / 1.07
        // VAT = ราคารวม - ราคาก่อน VAT
        totalVAT = totalBeforeVAT - (totalBeforeVAT / 1.07);
        grandTotal = totalBeforeVAT; // ราคาที่กรอกคือราคารวม VAT แล้ว
      } else {
        // VAT นอก: ราคา + VAT 7%
        totalVAT = totalBeforeVAT * 0.07;
        grandTotal = totalBeforeVAT + totalVAT;
      }
    } else {
      grandTotal = totalBeforeVAT;
    }
    
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: Colors.grey[100],
        borderRadius: BorderRadius.circular(8),
        border: Border.all(color: Colors.grey[300]!),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          ResponsiveText(
            'สรุปยอดรวม',
            style: const TextStyle(
              fontSize: 16,
              fontWeight: FontWeight.bold,
            ),
          ),
          const SizedBox(height: 12),
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              const Text('ยอดรวมก่อน VAT:'),
              Text(
                '฿${totalBeforeVAT.toStringAsFixed(2)}',
                style: const TextStyle(fontWeight: FontWeight.w500),
              ),
            ],
          ),
          if (_isVAT) ...[
            const SizedBox(height: 8),
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                const Text('VAT (7%):'),
                Text(
                  '฿${totalVAT.toStringAsFixed(2)}',
                  style: TextStyle(
                    color: Colors.green[700],
                    fontWeight: FontWeight.w500,
                  ),
                ),
              ],
            ),
          ],
          const SizedBox(height: 8),
          const Divider(),
          const SizedBox(height: 8),
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              const Text(
                'ยอดรวมที่ต้องจ่าย:',
                style: TextStyle(
                  fontSize: 16,
                  fontWeight: FontWeight.bold,
                ),
              ),
              Text(
                '฿${grandTotal.toStringAsFixed(2)}',
                style: const TextStyle(
                  fontSize: 18,
                  fontWeight: FontWeight.bold,
                  color: Colors.blue,
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  Widget _buildTextField({
    required TextEditingController controller,
    required String label,
    String? hint,
    int maxLines = 1,
    TextInputType? keyboardType,
    String? Function(String?)? validator,
    VoidCallback? onTap,
  }) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        ResponsiveText(
          label,
          style: const TextStyle(
            fontWeight: FontWeight.w500,
            fontSize: 14,
          ),
        ),
        const SizedBox(height: 8),
        TextFormField(
          controller: controller,
          decoration: InputDecoration(
            hintText: hint,
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(8),
            ),
            contentPadding: const EdgeInsets.symmetric(
              horizontal: 12,
              vertical: 12,
            ),
          ),
          maxLines: maxLines,
          keyboardType: keyboardType,
          validator: validator,
          onTap: onTap,
          readOnly: onTap != null,
        ),
      ],
    );
  }

  Widget _buildDateField({
    required TextEditingController controller,
    required String label,
    required VoidCallback onTap,
  }) {
    return _buildTextField(
      controller: controller,
      label: label,
      hint: 'เลือกวันที่',
      onTap: onTap,
    );
  }





  Future<void> _selectDate(TextEditingController controller) async {
    final DateTime? picked = await showDatePicker(
      context: context,
      initialDate: DateTime.now(),
      firstDate: DateTime(2020),
      lastDate: DateTime(2030),
    );
    if (picked != null) {
      controller.text = _formatDate(picked);
    }
  }

  String _formatDate(DateTime date) {
    return '${date.day.toString().padLeft(2, '0')}/${date.month.toString().padLeft(2, '0')}/${date.year}';
  }

  DateTime _parseDate(String dateStr) {
    try {
      final parts = dateStr.split('/');
      if (parts.length == 3) {
        return DateTime(
          int.parse(parts[2]), // year
          int.parse(parts[1]), // month
          int.parse(parts[0]), // day
        );
      }
    } catch (e) {
      // Fall back to now if parsing fails
    }
    return DateTime.now();
  }

  String _formatSupplierDisplay(Supplier supplier) {
    final parts = <String>[];
    
    // ชื่อบริษัท หรือ ชื่อผู้ติดต่อ
    if (supplier.companyName.isNotEmpty) {
      parts.add(supplier.companyName);
    } else if (supplier.contactName.isNotEmpty) {
      parts.add(supplier.contactName);
    }
    
    // รหัสซัพพลายเออร์
    if (supplier.supplierCode.isNotEmpty) {
      parts.add('[${supplier.supplierCode}]');
    }
    
    // ชื่อผู้ติดต่อ (ถ้ามีชื่อบริษัทแล้ว)
    if (supplier.companyName.isNotEmpty && supplier.contactName.isNotEmpty) {
      parts.add('- ${supplier.contactName}');
    }
    
    // เบอร์โทร
    if (supplier.phone.isNotEmpty) {
      parts.add('(${supplier.phone})');
    }
    
    return parts.join(' ');
  }

  Widget _buildActionButtons(bool isEdit) {
    return Row(
      children: [
        Expanded(
          child: OutlinedButton(
            onPressed: _isLoading ? null : () => context.go('/purchases'),
            child: const Text('ยกเลิก'),
          ),
        ),
        const SizedBox(width: 16),
        Expanded(
          child: ElevatedButton(
            onPressed: _isLoading ? null : _savePurchase,
            child: _isLoading
                ? const SizedBox(
                    width: 20,
                    height: 20,
                    child: CircularProgressIndicator(
                      strokeWidth: 2,
                      valueColor: AlwaysStoppedAnimation<Color>(Colors.white),
                    ),
                  )
                : Text(isEdit ? 'อัปเดต' : 'บันทึก'),
          ),
        ),
      ],
    );
  }

  void _addPurchaseItem() {
    showDialog(
      context: context,
      builder: (context) => _buildAddItemDialog(),
    );
  }

  Widget _buildAddItemDialog() {
    return Consumer<ProductProvider>(
      builder: (context, productProvider, child) {
        // แสดง loading indicator ถ้ากำลังโหลด
        if (productProvider.isLoading) {
          return AlertDialog(
            title: const Text('เพิ่มสินค้า'),
            content: const SizedBox(
              height: 100,
              child: Center(
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    CircularProgressIndicator(),
                    SizedBox(height: 16),
                    Text('กำลังโหลดข้อมูลสินค้า...'),
                  ],
                ),
              ),
            ),
          );
        }
        
        return AlertDialog(
          title: const Text('เพิ่มสินค้า'),
          content: SizedBox(
            width: double.maxFinite,
            child: _AddItemForm(
              products: productProvider.allProducts,
              onAdd: (item) {
                setState(() {
                  _purchaseItems.add(item);
                });
                Navigator.of(context).pop();
              },
            ),
          ),
        );
      },
    );
  }

  void _removePurchaseItem(int index) {
    setState(() {
      _purchaseItems.removeAt(index);
    });
  }

  void _copyFromPurchaseItems() {
    setState(() {
      _warehouseItems = _purchaseItems.map((item) => WarehouseItem(
        productId: item.productId,
        productName: item.productName,
        quantity: item.quantity,
        boxes: 1, // Default 1 box
        notes: null,
      )).toList();
    });
    
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(
        content: Text('คัดลอกรายการสินค้าจากการซื้อแล้ว'),
        backgroundColor: Colors.green,
      ),
    );
  }

  void _addWarehouseItem() {
    showDialog(
      context: context,
      builder: (context) => _buildAddWarehouseItemDialog(),
    );
  }

  Widget _buildAddWarehouseItemDialog() {
    return Consumer<ProductProvider>(
      builder: (context, productProvider, child) {
        // แสดง loading indicator ถ้ากำลังโหลด
        if (productProvider.isLoading) {
          return AlertDialog(
            title: const Text('เพิ่มสินค้าคลัง'),
            content: const SizedBox(
              height: 100,
              child: Center(
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    CircularProgressIndicator(),
                    SizedBox(height: 16),
                    Text('กำลังโหลดข้อมูลสินค้า...'),
                  ],
                ),
              ),
            ),
          );
        }
        
        return AlertDialog(
          title: const Text('เพิ่มสินค้าคลัง'),
          content: SizedBox(
            width: double.maxFinite,
            child: _AddWarehouseItemForm(
              products: productProvider.allProducts,
              onAdd: (item) {
                setState(() {
                  _warehouseItems.add(item);
                });
                Navigator.of(context).pop();
              },
            ),
          ),
        );
      },
    );
  }

  Widget _buildWarehouseItemRow(int index) {
    final item = _warehouseItems[index];
    
    return Container(
      key: ValueKey('warehouse_item_$index'),
      margin: const EdgeInsets.only(bottom: 12),
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(
        color: Colors.orange[50],
        borderRadius: BorderRadius.circular(8),
        border: Border.all(color: Colors.orange[200]!),
      ),
      child: Column(
        children: [
          Row(
            children: [
              Expanded(
                child: Text(
                  '${item.productName}',
                  style: const TextStyle(
                    fontWeight: FontWeight.bold,
                    color: Colors.orange,
                  ),
                ),
              ),
              IconButton(
                onPressed: () => _removeWarehouseItem(index),
                icon: const Icon(Icons.delete, color: Colors.red, size: 20),
                tooltip: 'ลบสินค้านี้',
              ),
            ],
          ),
          const SizedBox(height: 8),
          Row(
            children: [
              Expanded(
                child: TextFormField(
                  key: ValueKey('warehouse_quantity_$index'),
                  initialValue: item.quantity.toString(),
                  decoration: const InputDecoration(
                    labelText: 'จำนวน',
                    border: OutlineInputBorder(),
                    contentPadding: EdgeInsets.symmetric(horizontal: 8, vertical: 8),
                  ),
                  keyboardType: TextInputType.number,
                  onChanged: (value) {
                    final quantity = int.tryParse(value) ?? 0;
                    _warehouseItems[index] = WarehouseItem(
                      productId: _warehouseItems[index].productId,
                      productName: _warehouseItems[index].productName,
                      quantity: quantity,
                      boxes: _warehouseItems[index].boxes,
                      notes: _warehouseItems[index].notes,
                    );
                  },
                ),
              ),
              const SizedBox(width: 8),
              Expanded(
                child: TextFormField(
                  key: ValueKey('warehouse_boxes_$index'),
                  initialValue: item.boxes.toString(),
                  decoration: const InputDecoration(
                    labelText: 'ลัง',
                    border: OutlineInputBorder(),
                    contentPadding: EdgeInsets.symmetric(horizontal: 8, vertical: 8),
                  ),
                  keyboardType: TextInputType.number,
                  onChanged: (value) {
                    final boxes = int.tryParse(value) ?? 0;
                    _warehouseItems[index] = WarehouseItem(
                      productId: _warehouseItems[index].productId,
                      productName: _warehouseItems[index].productName,
                      quantity: _warehouseItems[index].quantity,
                      boxes: boxes,
                      notes: _warehouseItems[index].notes,
                    );
                  },
                ),
              ),
            ],
          ),
          const SizedBox(height: 8),
          TextFormField(
            key: ValueKey('warehouse_notes_$index'),
            initialValue: item.notes ?? '',
            decoration: const InputDecoration(
              labelText: 'หมายเหตุ',
              border: OutlineInputBorder(),
              contentPadding: EdgeInsets.symmetric(horizontal: 8, vertical: 8),
            ),
            maxLines: 2,
            onChanged: (value) {
              _warehouseItems[index] = WarehouseItem(
                productId: _warehouseItems[index].productId,
                productName: _warehouseItems[index].productName,
                quantity: _warehouseItems[index].quantity,
                boxes: _warehouseItems[index].boxes,
                notes: value.trim().isEmpty ? null : value.trim(),
              );
            },
          ),
        ],
      ),
    );
  }

  void _removeWarehouseItem(int index) {
    setState(() {
      _warehouseItems.removeAt(index);
    });
  }


  DateTime? _parsePaymentDate() {
    final dateText = _paymentDateController.text.trim();
    if (dateText.isEmpty) return null;
    
    try {
      // Parse DD/MM/YYYY format
      final parts = dateText.split('/');
      if (parts.length == 3) {
        final day = int.parse(parts[0]);
        final month = int.parse(parts[1]);
        final year = int.parse(parts[2]);
        return DateTime(year, month, day);
      }
    } catch (e) {
      // If parsing fails, return null
    }
    return null;
  }

  Future<void> _savePurchase() async {
    if (!_formKey.currentState!.validate()) {
      return;
    }

    if (_selectedSupplierId == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('กรุณาเลือกลูกค้า'),
          backgroundColor: Colors.red,
        ),
      );
      return;
    }

    if (_purchaseItems.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('กรุณาเพิ่มสินค้าในรายการ'),
          backgroundColor: Colors.red,
        ),
      );
      return;
    }

    setState(() {
      _isLoading = true;
    });

    try {
      final purchaseRequest = PurchaseRequest(
        purchaseDate: _parseDate(_purchaseDateController.text),
        supplierId: _selectedSupplierId!,
        invoiceNumber: _invoiceNumberController.text.trim().isEmpty ? null : _invoiceNumberController.text.trim(),
        notes: _notesController.text.trim().isEmpty ? null : _notesController.text.trim(),
        items: _purchaseItems,
        isVAT: _isVAT,
        vatType: _vatType,
        shippingCost: double.tryParse(_shippingCostController.text) ?? 0.0,
        payment: PaymentInfo(
          isPaid: _isPaid,
          paymentMethod: _paymentMethodController.text.trim().isEmpty ? null : _paymentMethodController.text.trim(),
          ourAccount: _selectedAccountId,
          customerAccount: _customerAccountController.text.trim().isEmpty ? null : _customerAccountController.text.trim(),
          paymentDate: _paymentDateController.text.trim().isEmpty ? null : _parsePaymentDate(),
        ),
        warehouse: WarehouseInfo(
          isUpdated: _isWarehouseUpdated,
          notes: _warehouseNotesController.text.trim().isEmpty ? null : _warehouseNotesController.text.trim(),
          actualShipping: double.tryParse(_actualShippingController.text) ?? 0.0,
          items: _warehouseItems.isEmpty ? [] : _warehouseItems,
        ),
      );

      final purchaseProvider = context.read<PurchaseProvider>();
      String? resultPurchaseId;
      
      if (_isEdit) {
        final purchaseId = widget.purchase?.id ?? widget.purchaseId!;
        final success = await purchaseProvider.updatePurchase(purchaseId, purchaseRequest);
        if (success) resultPurchaseId = purchaseId;
      } else {
        final newPurchase = await purchaseProvider.addPurchase(purchaseRequest);
        resultPurchaseId = newPurchase?.id;
      }

      if (resultPurchaseId != null && mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(
              _isEdit 
                  ? 'อัปเดตรายการซื้อเรียบร้อยแล้ว' 
                  : 'เพิ่มรายการซื้อเรียบร้อยแล้ว',
            ),
            backgroundColor: Colors.green,
          ),
        );
        
        // Redirect to purchase detail page (both create and edit)
        context.go('/purchase/$resultPurchaseId');
      } else if (mounted) {
        // Show error popup if not successful
        final errorMessage = purchaseProvider.error;
        ErrorDialog.showServerError(context, errorMessage);
      }
    } catch (e) {
      if (mounted) {
        ErrorDialog.showServerError(context, 'เกิดข้อผิดพลาด: $e');
      }
    } finally {
      if (mounted) {
        setState(() {
          _isLoading = false;
        });
      }
    }
  }
}

class _AddItemForm extends StatefulWidget {
  final List<Product> products;
  final Function(PurchaseItem) onAdd;

  const _AddItemForm({
    required this.products,
    required this.onAdd,
  });

  @override
  State<_AddItemForm> createState() => _AddItemFormState();
}

class _AddItemFormState extends State<_AddItemForm> {
  final _formKey = GlobalKey<FormState>();
  Product? _selectedProduct;
  Product? _selectedPreform;
  final _quantityController = TextEditingController();
  final _unitPriceController = TextEditingController();

  // Get preform products (category = "พรีฟอร์ม")
  List<Product> get _preformProducts {
    return widget.products.where((product) => product.category == 'พรีฟอร์ม').toList();
  }

  @override
  void dispose() {
    _quantityController.dispose();
    _unitPriceController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Form(
      key: _formKey,
      child: Column(
        mainAxisSize: MainAxisSize.min,
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          // Product Selection
          SearchableDropdown<Product>(
            value: _selectedProduct,
            items: widget.products,
            itemAsString: (product) => '${product.name} (${product.code})',
            onChanged: (product) {
              setState(() {
                _selectedProduct = product;
              });
            },
            hint: 'เลือกสินค้า',
            label: 'เลือกสินค้า *',
            validator: (value) {
              if (value == null) {
                return 'กรุณาเลือกสินค้า';
              }
              return null;
            },
            prefixIcon: const Icon(Icons.inventory),
          ),
          
          const SizedBox(height: 16),
          
          // Quantity
          TextFormField(
            controller: _quantityController,
            decoration: const InputDecoration(
              labelText: 'จำนวน *',
              border: OutlineInputBorder(),
            ),
            keyboardType: TextInputType.number,
            validator: (value) {
              if (value == null || value.trim().isEmpty) {
                return 'กรุณากรอกจำนวน';
              }
              if (int.tryParse(value) == null || int.parse(value) <= 0) {
                return 'กรุณากรอกจำนวนที่ถูกต้อง';
              }
              return null;
            },
          ),
          
          const SizedBox(height: 16),
          
          // Unit Price
          TextFormField(
            controller: _unitPriceController,
            decoration: const InputDecoration(
              labelText: 'ราคาต่อชิ้น *',
              border: OutlineInputBorder(),
            ),
            keyboardType: const TextInputType.numberWithOptions(decimal: true),
            validator: (value) {
              if (value == null || value.trim().isEmpty) {
                return 'กรุณากรอกราคา';
              }
              if (double.tryParse(value) == null || double.parse(value) <= 0) {
                return 'กรุณากรอกราคาที่ถูกต้อง';
              }
              return null;
            },
          ),
          
          const SizedBox(height: 16),
          
          // Preform Selection (Optional)
          if (_preformProducts.isNotEmpty)
            SearchableDropdown<Product>(
              value: _selectedPreform,
              items: _preformProducts,
              itemAsString: (product) => '${product.name} (${product.code})',
              onChanged: (product) {
                setState(() {
                  _selectedPreform = product;
                });
              },
              hint: 'เลือกพรีฟอร์ม (ไม่บังคับ)',
              label: 'พรีฟอร์ม',
              prefixIcon: const Icon(Icons.inventory_2),
            ),
          
          const SizedBox(height: 24),
          
          // Action Buttons
          Row(
            children: [
              Expanded(
                child: OutlinedButton(
                  onPressed: () => Navigator.of(context).pop(),
                  child: const Text('ยกเลิก'),
                ),
              ),
              const SizedBox(width: 16),
              Expanded(
                child: ElevatedButton(
                  onPressed: _addItem,
                  child: const Text('เพิ่ม'),
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  void _addItem() {
    if (!_formKey.currentState!.validate()) {
      return;
    }

    if (_selectedProduct == null) {
      return;
    }

    final quantity = int.parse(_quantityController.text);
    final unitPrice = double.parse(_unitPriceController.text);
    
    // Calculate total price: unitPrice * quantity (ไม่รวม preform cost)
    // Preform cost จะถูกใช้ในการคำนวณต้นทุนเฉลี่ยที่ backend เท่านั้น
    double preformUnitPrice = 0.0;
    if (_selectedPreform != null) {
      // Use the latest purchase price of preform
      if (_selectedPreform!.price.purchaseVAT.latest > 0) {
        preformUnitPrice = _selectedPreform!.price.purchaseVAT.latest;
      } else if (_selectedPreform!.price.purchaseNonVAT.latest > 0) {
        preformUnitPrice = _selectedPreform!.price.purchaseNonVAT.latest;
      }
    }
    
    // totalPrice แสดงราคาไม่รวม preform (สำหรับแสดงใน UI)
    // แต่ preformUnitPrice จะถูกส่งไป backend เพื่อคำนวณต้นทุนเฉลี่ย
    final totalPrice = unitPrice * quantity;

    final item = PurchaseItem(
      productId: _selectedProduct!.id,
      productName: _selectedProduct!.name,
      productCode: _selectedProduct!.code,
      quantity: quantity,
      unitPrice: unitPrice,
      preformProductId: _selectedPreform?.id,
      preformUnitPrice: _selectedPreform != null ? preformUnitPrice : null,
      totalPrice: totalPrice,
    );

    widget.onAdd(item);
  }
}

class _AddWarehouseItemForm extends StatefulWidget {
  final List<Product> products;
  final Function(WarehouseItem) onAdd;

  const _AddWarehouseItemForm({
    required this.products,
    required this.onAdd,
  });

  @override
  State<_AddWarehouseItemForm> createState() => _AddWarehouseItemFormState();
}

class _AddWarehouseItemFormState extends State<_AddWarehouseItemForm> {
  final _formKey = GlobalKey<FormState>();
  Product? _selectedProduct;
  final _quantityController = TextEditingController();
  final _boxesController = TextEditingController();
  final _notesController = TextEditingController();

  @override
  void dispose() {
    _quantityController.dispose();
    _boxesController.dispose();
    _notesController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Form(
      key: _formKey,
      child: Column(
        mainAxisSize: MainAxisSize.min,
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          // Product Selection
          SearchableDropdown<Product>(
            value: _selectedProduct,
            items: widget.products,
            itemAsString: (product) => '${product.name} (${product.code})',
            onChanged: (product) {
              setState(() {
                _selectedProduct = product;
              });
            },
            hint: 'เลือกสินค้า',
            label: 'เลือกสินค้า *',
            validator: (value) {
              if (value == null) {
                return 'กรุณาเลือกสินค้า';
              }
              return null;
            },
            prefixIcon: const Icon(Icons.inventory),
          ),
          
          const SizedBox(height: 16),
          
          // Quantity
          TextFormField(
            controller: _quantityController,
            decoration: const InputDecoration(
              labelText: 'จำนวน *',
              border: OutlineInputBorder(),
            ),
            keyboardType: TextInputType.number,
            validator: (value) {
              if (value == null || value.trim().isEmpty) {
                return 'กรุณากรอกจำนวน';
              }
              if (int.tryParse(value) == null || int.parse(value) <= 0) {
                return 'กรุณากรอกจำนวนที่ถูกต้อง';
              }
              return null;
            },
          ),
          
          const SizedBox(height: 16),
          
          // Boxes
          TextFormField(
            controller: _boxesController,
            decoration: const InputDecoration(
              labelText: 'จำนวนลัง',
              border: OutlineInputBorder(),
            ),
            keyboardType: TextInputType.number,
            validator: (value) {
              if (value != null && value.trim().isNotEmpty) {
                if (int.tryParse(value) == null || int.parse(value) < 0) {
                  return 'กรุณากรอกจำนวนลังที่ถูกต้อง';
                }
              }
              return null;
            },
          ),
          
          const SizedBox(height: 16),
          
          // Notes
          TextFormField(
            controller: _notesController,
            decoration: const InputDecoration(
              labelText: 'หมายเหตุ',
              border: OutlineInputBorder(),
            ),
            maxLines: 2,
          ),
          
          const SizedBox(height: 24),
          
          // Action Buttons
          Row(
            children: [
              Expanded(
                child: OutlinedButton(
                  onPressed: () => Navigator.of(context).pop(),
                  child: const Text('ยกเลิก'),
                ),
              ),
              const SizedBox(width: 16),
              Expanded(
                child: ElevatedButton(
                  onPressed: _addItem,
                  child: const Text('เพิ่ม'),
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  void _addItem() {
    if (!_formKey.currentState!.validate()) {
      return;
    }

    if (_selectedProduct == null) {
      return;
    }

    final quantity = int.parse(_quantityController.text);
    final boxes = int.tryParse(_boxesController.text) ?? 0;
    final notes = _notesController.text.trim().isEmpty ? null : _notesController.text.trim();

    final item = WarehouseItem(
      productId: _selectedProduct!.id,
      productName: _selectedProduct!.name,
      quantity: quantity,
      boxes: boxes,
      notes: notes,
    );

    widget.onAdd(item);
  }
}
