import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:go_router/go_router.dart';
import '../models/supplier.dart';
import '../providers/supplier_provider.dart';
import '../widgets/responsive_layout.dart';
import '../utils/error_dialog.dart';

class SupplierFormScreen extends StatefulWidget {
  final Supplier? supplier;
  final String? supplierId;
  final String? duplicateId;

  const SupplierFormScreen({Key? key, this.supplier, this.supplierId, this.duplicateId}) : super(key: key);

  @override
  State<SupplierFormScreen> createState() => _SupplierFormScreenState();
}

class _SupplierFormScreenState extends State<SupplierFormScreen> {
  final _formKey = GlobalKey<FormState>();
  final _companyNameController = TextEditingController();
  final _contactNameController = TextEditingController();
  final _taxIdController = TextEditingController();
  final _phoneController = TextEditingController();
  final _addressController = TextEditingController();
  final _contactMethodController = TextEditingController();

  bool _isLoading = false;
  bool get _isEdit => widget.supplier != null || widget.supplierId != null;

  @override
  void initState() {
    super.initState();
    _initializeForm();
  }

  void _initializeForm() {
    if (widget.supplier != null) {
      _populateFields();
    } else if (widget.supplierId != null) {
      _loadSupplierFromId();
    } else if (widget.duplicateId != null) {
      _loadDuplicateSupplier();
    }
  }

  void _loadDuplicateSupplier() {
    WidgetsBinding.instance.addPostFrameCallback((_) async {
      final supplierProvider = context.read<SupplierProvider>();
      
      if (supplierProvider.allSuppliers.isEmpty) {
        await supplierProvider.loadSuppliers();
      }
      
      final supplier = supplierProvider.getSupplierById(widget.duplicateId!);
      if (supplier != null) {
        _populateFieldsForDuplicate(supplier);
      }
    });
  }

  void _populateFieldsForDuplicate(Supplier supplier) {
    // Copy all fields except supplierCode (will be generated by server)
    _companyNameController.text = '${supplier.companyName} (สำเนา)';
    _contactNameController.text = supplier.contactName;
    _taxIdController.text = ''; // Clear tax ID as it should be unique
    _phoneController.text = supplier.phone;
    _addressController.text = supplier.address;
    _contactMethodController.text = supplier.contactMethod;
    
    if (mounted) {
      setState(() {});
    }
  }

  void _loadSupplierFromId() {
    WidgetsBinding.instance.addPostFrameCallback((_) {
      final supplier = context.read<SupplierProvider>().getSupplierById(widget.supplierId!);
      if (supplier != null) {
        _populateFieldsFromSupplier(supplier);
      }
    });
  }

  void _populateFieldsFromSupplier(Supplier supplier) {
    _companyNameController.text = supplier.companyName;
    _contactNameController.text = supplier.contactName;
    _taxIdController.text = supplier.taxId;
    _phoneController.text = supplier.phone;
    _addressController.text = supplier.address;
    _contactMethodController.text = supplier.contactMethod;
    
    if (mounted) {
      setState(() {});
    }
  }

  void _populateFields() {
    final supplier = widget.supplier!;
    _populateFieldsFromSupplier(supplier);
  }

  @override
  void dispose() {
    _companyNameController.dispose();
    _contactNameController.dispose();
    _taxIdController.dispose();
    _phoneController.dispose();
    _addressController.dispose();
    _contactMethodController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final supplierId = widget.supplier?.id ?? widget.supplierId;
    
    return Scaffold(
      appBar: ResponsiveAppBar(
        title: _isEdit ? 'แก้ไขซัพพลายเออร์' : 'เพิ่มซัพพลายเออร์ใหม่',
        leading: _isEdit && supplierId != null
            ? IconButton(
                icon: const Icon(Icons.arrow_back),
                onPressed: () => context.pop(),
                tooltip: 'กลับไปหน้ารายละเอียด',
              )
            : null,
        actions: [
          if (_isLoading)
            const Padding(
              padding: EdgeInsets.all(16),
              child: SizedBox(
                width: 20,
                height: 20,
                child: CircularProgressIndicator(strokeWidth: 2),
              ),
            ),
        ],
      ),
      body: Form(
        key: _formKey,
        child: ResponsivePadding(
          child: SingleChildScrollView(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                // Form Fields
                _buildFormFields(),
                
                const SizedBox(height: 32),
                
                // Action Buttons
                _buildActionButtons(_isEdit),
              ],
            ),
          ),
        ),
      ),
    );
  }

  Widget _buildFormFields() {
    return Card(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            ResponsiveText(
              'ข้อมูลซัพพลายเออร์',
              style: const TextStyle(
                fontSize: 16,
                fontWeight: FontWeight.bold,
              ),
            ),
            const SizedBox(height: 16),
            
            // Company Name
            _buildTextField(
              controller: _companyNameController,
              label: 'ชื่อบริษัท',
              hint: 'กรอกชื่อบริษัท',
            ),
            
            const SizedBox(height: 16),
            
            // Contact Name
            _buildTextField(
              controller: _contactNameController,
              label: 'ชื่อผู้ติดต่อ *',
              hint: 'กรอกชื่อผู้ติดต่อ',
              validator: (value) {
                if (value == null || value.trim().isEmpty) {
                  return 'กรุณากรอกชื่อผู้ติดต่อ';
                }
                return null;
              },
            ),
            
            const SizedBox(height: 16),
            
            // Tax ID
            _buildTextField(
              controller: _taxIdController,
              label: 'เลขที่ผู้เสียภาษี',
              hint: 'กรอกเลขที่ผู้เสียภาษี',
            ),
            
            const SizedBox(height: 16),
            
            // Phone
            _buildTextField(
              controller: _phoneController,
              label: 'เบอร์โทร *',
              hint: 'กรอกเบอร์โทร',
              keyboardType: TextInputType.phone,
              validator: (value) {
                if (value == null || value.trim().isEmpty) {
                  return 'กรุณากรอกเบอร์โทร';
                }
                return null;
              },
            ),
            
            const SizedBox(height: 16),
            
            // Address
            _buildTextField(
              controller: _addressController,
              label: 'ที่อยู่',
              hint: 'กรอกที่อยู่',
              maxLines: 3,
            ),
            
            const SizedBox(height: 16),
            
            // Contact Method
            _buildTextField(
              controller: _contactMethodController,
              label: 'ช่องทางติดต่อ',
              hint: 'เช่น อีเมล, Line, Facebook',
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildTextField({
    required TextEditingController controller,
    required String label,
    String? hint,
    int maxLines = 1,
    TextInputType? keyboardType,
    String? Function(String?)? validator,
  }) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        ResponsiveText(
          label,
          style: const TextStyle(
            fontWeight: FontWeight.w500,
            fontSize: 14,
          ),
        ),
        const SizedBox(height: 8),
        TextFormField(
          controller: controller,
          decoration: InputDecoration(
            hintText: hint,
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(8),
            ),
            contentPadding: const EdgeInsets.symmetric(
              horizontal: 12,
              vertical: 12,
            ),
          ),
          maxLines: maxLines,
          keyboardType: keyboardType,
          validator: validator,
        ),
      ],
    );
  }

  Widget _buildActionButtons(bool isEdit) {
    return Row(
      children: [
        Expanded(
          child: OutlinedButton(
            onPressed: _isLoading ? null : () => context.go('/suppliers'),
            child: const Text('ยกเลิก'),
          ),
        ),
        const SizedBox(width: 16),
        Expanded(
          child: ElevatedButton(
            onPressed: _isLoading ? null : _saveSupplier,
            child: _isLoading
                ? const SizedBox(
                    width: 20,
                    height: 20,
                    child: CircularProgressIndicator(
                      strokeWidth: 2,
                      valueColor: AlwaysStoppedAnimation<Color>(Colors.white),
                    ),
                  )
                : Text(isEdit ? 'อัปเดต' : 'บันทึก'),
          ),
        ),
      ],
    );
  }

  Future<void> _saveSupplier() async {
    if (!_formKey.currentState!.validate()) {
      return;
    }

    setState(() {
      _isLoading = true;
    });

    try {
      final supplierRequest = SupplierRequest(
        companyName: _companyNameController.text.trim(),
        contactName: _contactNameController.text.trim(),
        taxId: _taxIdController.text.trim(),
        phone: _phoneController.text.trim(),
        address: _addressController.text.trim(),
        contactMethod: _contactMethodController.text.trim(),
      );

      final supplierProvider = context.read<SupplierProvider>();
      String? resultSupplierId;
      
      if (_isEdit) {
        final supplierId = widget.supplier?.id ?? widget.supplierId!;
        final success = await supplierProvider.updateSupplier(supplierId, supplierRequest);
        if (success) resultSupplierId = supplierId;
      } else {
        final newSupplier = await supplierProvider.addSupplier(supplierRequest);
        resultSupplierId = newSupplier?.id;
      }

      if (resultSupplierId != null && mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(
              _isEdit 
                  ? 'อัปเดตซัพพลายเออร์เรียบร้อยแล้ว' 
                  : 'เพิ่มซัพพลายเออร์เรียบร้อยแล้ว',
            ),
            backgroundColor: Colors.green,
          ),
        );
        
        // Redirect to supplier detail page (both create and edit)
        context.go('/supplier/$resultSupplierId');
      } else if (mounted) {
        // Show error popup if not successful
        final errorMessage = supplierProvider.error;
        ErrorDialog.showServerError(context, errorMessage);
      }
    } catch (e) {
      if (mounted) {
        ErrorDialog.showServerError(context, 'เกิดข้อผิดพลาด: $e');
      }
    } finally {
      if (mounted) {
        setState(() {
          _isLoading = false;
        });
      }
    }
  }
}

